spring:
  datasource:
    url: jdbc:mysql://bobchadoo.ddns.net:8312/ydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: "gpals"
    password: "!Dnfl578657"
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8102  # PORT





